# Generated by Django 3.2.6 on 2021-08-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scales', '0002_auto_20210816_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recorde',
            new_name='record',
        ),
    ]
